### ISSUE TITLE
generate_dynamic_reconfigure_options() generates files in the source tree

### ISSUE THREAD

**Issue by jbohren** [ros/dynamic_reconfigure#10]
Currently, dynamic_reconfigure generates config files in the source tree, but shouldn't it do so in the devel tree?

https://github.com/ros/dynamic_reconfigure/blob/master/cmake/cfgbuild.cmake#L56

**Comment by OkkeHendriks** [comment]
It is not? I am seeing that the cpp and doc output is generated in source directory.
Using the following in my CMakeLists.txt
```
## Generate dynamic reconfigure parameters in the 'cfg' folder
generate_dynamic_reconfigure_options(
  cfg/node_example_params.cfg
)
```

**Comment by MFernandezCarmona** [comment]
I can confirm that behaviour. How are we supposed to include those cpp and h files in the corresponding nodes?
