### ISSUE TITLE
rostest times out on Debian Stretch and recent ubuntus

### ISSUE THREAD

**Issue by mikaelarguedas** [ros/dynamic_reconfigure#103]
This seem to be Ubuntu Distro related and not ROS Distro related, consistently fails on Debian Stretch, Ubuntu Artful and Bionic.
Example jobs with hanging test: http://build.ros.org/view/Mdev/job/Mdev__dynamic_reconfigure__ubuntu_bionic_amd64/1/
http://build.ros.org/view/Mdev_ds/job/Mdev_ds__dynamic_reconfigure__debian_stretch_amd64/1/

**Comment by krixkrix** [comment]
On debian stretch this test fails for me as well:

> rostest dynamic_reconfigure test_cpp_simple_client.launch

Or to be accurate: all tests passes but the test itself times out.

If I change this line in test_client.cpp:

`ros::AsyncSpinner spinner(2);`

To:

`ros::AsyncSpinner spinner(1);`

...then the tests succeeds.

**Comment by mikaelarguedas** [comment]
thanks @krixkrix for looking into it!

I opened https://github.com/ros/dynamic_reconfigure/pull/119 that should address the test failure without modifying the number of threads used by the spinner.
