### ISSUE TITLE
hope can add a new feature

### ISSUE THREAD

**Issue by Chrislzy1993** [ros/dynamic_reconfigure#127]
sorry, it is not a issue, just an advice.  if you can add a button which can change the value by a constant value, or this package have this function,   where can i find it

**Comment by mjcarroll** [comment]
This package is used for adding `dynamic_reconfigure` capabilities to a ROS node.  That is to say that it provides a mechanism for firing callbacks when parameters are changed external to the ROS node itself.  

You could create an additional executable that implements the behavior you describe using dynamic_reconfigure.

In the future, these type of questions are best asked on answers.ros.org, per our support guidelines.
