### ISSUE TITLE
setCallback() should not trigger the callback

### ISSUE THREAD

**Issue by bit-pirate** [ros/dynamic_reconfigure#13]
In my use case I have already set up all parameters from a config file. But they get overwritten with the defaults in the dynamic reconfigure config, when it is set up.

Is it possible to do setCallback without triggering it?

**Comment by esteve** [comment]
Thanks @Faedrivin for your suggestion. Checking for `level == -1` solves the issue, @bit-pirate In https://github.com/ros/dynamic_reconfigure/blob/master/include/dynamic_reconfigure/server.h#L89, the callback is called with `~0`(i.e. `level == -1`).

@bit-pirate please let us know if you'd prefer a different workaround, and please reopen this issue if so. Thanks.
