### ISSUE TITLE
Fail in yaml.load_all()

### ISSUE THREAD

**Issue by albertgassol1** [ros/dynamic_reconfigure#183]
When running the dynamic_reconfigure the process dies with the following error: `yaml.load_all() without loader=... is deprecated`

I had to change line 162 from `for doc in yaml.load_all(f.read()):` to `for doc in yaml.load_all(f.read(), Loader=yaml.Loader):`
With this change everything works properly.

**Comment by janbernloehr** [comment]
Should be fixed by #178
