### ISSUE TITLE
Commandline dynparam takes a few second to do "get"

### ISSUE THREAD

**Issue by 130s** [ros/dynamic_reconfigure#2]
Example
```
$ time rosrun dynamic_reconfigure dynparam get /wide_stereo_right
:
real	0m3.799s
user	0m2.084s
sys	0m0.308s
```

As far as experienced, this isn't the case with its python API `dynamic_reconfigure.client.Client` that can get node of 150+ in about 30 secs for `rqt_reconfigure`, which means 0.2 sec per each node (including other GUI tasks). If the same level of speed is realized that would be great.

amd64 Version: 1.5.31-0quantal-20130126-0941-+0000

**Comment by esteve** [comment]
Closing, seems to be fixed in the latest revision of `dynamic_reconfigure`. Please reopen if this bug persists.

Thanks.
