### ISSUE TITLE
Parameter oscillation when using rqt_reconfigure

### ISSUE THREAD

**Issue by skohlbr** [ros/dynamic_reconfigure#34]
I have observed this when using dynamic_reconfigure multiple times on completely unrelated robot systems, so I´m pretty sure it´s not just related to a specific setup: Sometimes when changing parameters, they will start oscillating between two different settings, with the slider in the user interface happily alternating between two settings at high frequency. By typing something into the SpinBox in the UI and pressing "Enter" multiple times, the issue can be "fixed" most of the time. There appears to be some kind of race condition happening between UI and target node, so it´s a bit hard to say which component is at fault.

This bug makes it very risky to use dynamic reconfiguration in many cases (say, controller parameter settings). Tested on 12.04/hydro/AMD64 from .debs with different nodes using dynamic_reconfigure.

**Comment by esteve** [comment]
Fixed in `rqt_common_plugins`, please reopen if the bug persists.

Thanks.
