### ISSUE TITLE
Install uses different name than auto gen header

### ISSUE THREAD

**Issue by dcconner** [ros/dynamic_reconfigure#37]
The cfg file (e.g. my_parameter.cfg) allows you to specify the name of generated header (e.g. MyParameter) in generate macro, and generates MyParameterConfig, but install  looks for name based off of configuration file name. 

Thus, when installing  I get a build error that system can't find my_parameterConfig.h

Work around by naming file the same as macro for now.

**Comment by esteve** [comment]
On a second thought, this isn't actually a bug in the code, but a lack of documentation in ParameterGenerator.generate(). I added a comment about how `name` must match the config file.

Thanks for reporting this.
