### ISSUE TITLE
Using dynparam from C++ code

### ISSUE THREAD

**Issue by DLu** [ros/dynamic_reconfigure#4]
As per <a href="http://www.ros.org/wiki/hokuyo_node/Tutorials/UsingDynparamToChangeHokuyoLaserParameters#Using_dynparam_from_C.2B-.2B-_code">the tutorial</a>, using dynparam from C++ code is not implemented.

**Comment by awesomebytes** [comment]
Anyone interested in implementing it? I was surprised to discover this is not available.

**Comment by jacquelinekay** [comment]
this would be great for ros/robot_state_publisher#29...

maybe I'll take a look

**Comment by kunaltyagi** [comment]
Any updates? I might be able to help.

**Comment by bit-pirate** [comment]
*upvote* :-)

**Comment by progtologist** [comment]
@mikaelarguedas This should also now close :-)

**Comment by mikaelarguedas** [comment]
indeed, thanks

**Comment by awesomebytes** [comment]
Great news!

**Comment by bit-pirate** [comment]
@progtologist thanks for this great addition!
@mikaelarguedas could we get a brief update here when (and for what distribution) this has been released?

**Comment by mikaelarguedas** [comment]
None of the ros_base packages will branch out for lunar. So all new features will be available for every active ros distribution.
A synchronized release will happen in the next few days
