### ISSUE TITLE
Many compile warnings due to unused parameters.

### ISSUE THREAD

**Issue by aleeper** [ros/dynamic_reconfigure#50]
The `config_tools.h` header has many used variables, resulting in a lot of compile warnings (on 14.04 with gcc 4.8.2) when we build our own code that includes these headers. This is not production-friendly :(

Lines:
15, 20, 25, 30, 35, 40, 45, 50

Not sure if there's a preferred style in the ROS code base, but I'd recommend commenting out the variable name, e.g.
```
static std::vector<dynamic_reconfigure::DoubleParameter>& getVectorForType(dynamic_reconfigure::Config &set, const double /*val*/)
```

Thanks!

**Comment by esteve** [comment]
I just pushed a PR (#52) that should remove the warnings, let me know if it works for you.

Thanks!
