### ISSUE TITLE
New check of description is causing other ros package to fail

### ISSUE THREAD

**Issue by tspicer01** [ros/dynamic_reconfigure#75]
We are seeing errors running with the latest version of dynamic_reconfigure as the new check is causing failures.   The latest version of ros image_transport_plugins (1.9.5) fails with the following error:

 ```
File "/tmp/buildd/workspace/dynamic_reconfigure/parameter_generator_catkin.py", line 70, in check_description
raise Exception(r"""quotes not allowed in description string `%s`""" % description)
Exception: quotes not allowed in description string `Try to achieve either 'target_bitrate' or 'quality'`
make[4]: *** [/tmp/buildd/workspace/theora_image_transport/include/theora_image_transport/TheoraPublisherConfig.h] Error 1
```

Is there a way to allow for backward compatibility or before turning the check on ensure that all other packages are compliant?

Any help with this would be appreciated.

@mikepurvis

**Comment by mikaelarguedas** [comment]
Thanks @tspicer01 for reporting it and the pointer. The check may be too restrictive. I'll perform some testing and get back to you.

**Comment by mikaelarguedas** [comment]
@tspicer01 @mikepurvis Sorry for the trouble, #76 should fix it, I tried it on desktop_full and it built fine. Can you try it on your side and comment here with your results ? Thanks!

**Comment by tspicer01** [comment]
Thanks for the quick response and turnaround.

I've tried it on our end and using your branch from #76 the packages that were failing are now successful.

**Comment by mikaelarguedas** [comment]
Great, thanks for testing it!
