### ISSUE TITLE
getCurrentConfiguration() sometimes fails in new cpp client

### ISSUE THREAD

**Issue by JVSelvag** [ros/dynamic_reconfigure#81]
In client.h: getCurrentConfiguration() sometimes fails to get the current configuration from the dynamic reconfigure server if the server has been recently updated with a new configuration.

A call to getCurrentConfiguration() will return when the "received_configuration_" boolean flag is true. 
However, this flag is only set to false in the constructor, so getCurrentConfiguration() will only work correctly the first time. Thereafter it will always return immediately, and not wait for the callback from the server update.

Possible workaround: Set "received_configuration_" to false in the method setConfiguration().

**Comment by JVSelvag** [comment]
Also in client.h: getDescription() suffers from the same problem. Here, the boolean flag "received_description_" is only set to false in the constructor of the Client() class.

**Comment by JVSelvag** [comment]
However, since the description won't change, getDescription() might work as it is...

**Comment by mikaelarguedas** [comment]
Thanks @JVSelvag for reporting this. #82 should fix it
